-- Secure the existing real-time classroom chat and expose one membership-aware
-- RPC. Browser clients cannot choose another user's display name or post into a
-- room they do not belong to.

DROP POLICY IF EXISTS "Users can send messages" ON public.classroom_messages;
REVOKE INSERT, UPDATE, DELETE ON public.classroom_messages FROM anon, authenticated;

ALTER TABLE public.classroom_messages
  DROP CONSTRAINT IF EXISTS classroom_messages_message_length_check;
ALTER TABLE public.classroom_messages
  ADD CONSTRAINT classroom_messages_message_length_check
  CHECK (length(trim(message)) BETWEEN 1 AND 1000) NOT VALID;

CREATE INDEX IF NOT EXISTS classroom_messages_room_created_idx
  ON public.classroom_messages(room_id, created_at DESC);

-- Security-definer membership helpers keep policies simple and avoid recursive
-- classes <-> class_members RLS evaluation.
CREATE OR REPLACE FUNCTION public.is_class_teacher(_class_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT auth.uid() IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.classes c WHERE c.id = _class_id AND c.teacher_id = auth.uid()
  );
$$;

CREATE OR REPLACE FUNCTION public.is_class_participant(_class_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT auth.uid() IS NOT NULL AND (
    public.is_class_teacher(_class_id)
    OR EXISTS (
      SELECT 1 FROM public.class_members cm
      WHERE cm.class_id = _class_id AND cm.user_id = auth.uid()
    )
  );
$$;

REVOKE ALL ON FUNCTION public.is_class_teacher(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.is_class_participant(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_class_teacher(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_class_participant(uuid) TO authenticated, service_role;

-- Joining must go through a code-aware server function. The former INSERT
-- policy only checked that users inserted their own id and did not prove that
-- they knew the class join code.
DROP POLICY IF EXISTS "Students can join classes" ON public.class_members;

CREATE TABLE IF NOT EXISTS public.class_join_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  attempted_at timestamptz NOT NULL DEFAULT now(),
  succeeded boolean NOT NULL DEFAULT false
);

ALTER TABLE public.class_join_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.class_join_attempts FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.class_join_attempts TO service_role;
CREATE INDEX IF NOT EXISTS class_join_attempts_user_time_idx
  ON public.class_join_attempts(user_id, attempted_at DESC);

CREATE OR REPLACE FUNCTION public.join_class_by_code(_join_code text)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid := auth.uid();
  clean_code text := lower(trim(coalesce(_join_code, '')));
  matched_class_id uuid;
BEGIN
  IF actor IS NULL THEN
    RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
  END IF;
  IF clean_code !~ '^[a-z0-9]{6,12}$' THEN
    RETURN NULL;
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext(actor::text));
  DELETE FROM public.class_join_attempts
  WHERE user_id = actor AND attempted_at < now() - interval '1 day';

  IF (
    SELECT count(*) FROM public.class_join_attempts attempt
    WHERE attempt.user_id = actor
      AND attempt.attempted_at > now() - interval '1 minute'
  ) >= 10 THEN
    RAISE EXCEPTION 'Join-code rate limit reached' USING ERRCODE = '42900';
  END IF;

  SELECT c.id INTO matched_class_id
  FROM public.classes AS c
  WHERE lower(c.join_code) = clean_code
  LIMIT 1;

  INSERT INTO public.class_join_attempts(user_id, succeeded)
  VALUES (actor, matched_class_id IS NOT NULL);

  IF matched_class_id IS NULL THEN
    RETURN NULL;
  END IF;

  INSERT INTO public.class_members(class_id, user_id)
  VALUES (matched_class_id, actor)
  ON CONFLICT (class_id, user_id) DO NOTHING;

  RETURN matched_class_id;
END;
$$;

REVOKE ALL ON FUNCTION public.join_class_by_code(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.join_class_by_code(text) TO authenticated, service_role;

DROP POLICY IF EXISTS "Students can view joined classes" ON public.classes;
CREATE POLICY "Students can view joined classes" ON public.classes
  FOR SELECT TO authenticated USING (public.is_class_participant(id));

DROP POLICY IF EXISTS "Teachers can manage class members" ON public.class_members;
CREATE POLICY "Teachers can manage class members" ON public.class_members
  FOR ALL TO authenticated
  USING (public.is_class_teacher(class_id))
  WITH CHECK (public.is_class_teacher(class_id));

DROP POLICY IF EXISTS "Class members can read classroom messages" ON public.classroom_messages;
CREATE POLICY "Class members can read classroom messages" ON public.classroom_messages
  FOR SELECT TO authenticated
  USING (
    room_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    AND public.is_class_participant(room_id::uuid)
  );

CREATE OR REPLACE FUNCTION public.send_classroom_message(
  _room_id uuid,
  _message text
)
RETURNS public.classroom_messages
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid := auth.uid();
  clean_message text := trim(coalesce(_message, ''));
  actor_name text;
  sent public.classroom_messages%ROWTYPE;
BEGIN
  IF actor IS NULL THEN
    RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
  END IF;
  IF length(clean_message) NOT BETWEEN 1 AND 1000 THEN
    RAISE EXCEPTION 'Message must contain 1 to 1000 characters' USING ERRCODE = '22023';
  END IF;
  IF NOT public.is_class_participant(_room_id) THEN
    RAISE EXCEPTION 'Class membership required' USING ERRCODE = '42501';
  END IF;

  -- Serialize each sender's posts so parallel requests cannot bypass the
  -- per-minute threshold.
  PERFORM pg_advisory_xact_lock(hashtext(actor::text));
  IF (
    SELECT count(*) FROM public.classroom_messages m
    WHERE m.user_id = actor AND m.created_at > now() - interval '1 minute'
  ) >= 12 THEN
    RAISE EXCEPTION 'Message rate limit reached' USING ERRCODE = '42900';
  END IF;

  SELECT nullif(trim(p.display_name), '') INTO actor_name
  FROM public.profiles p
  WHERE p.user_id = actor;

  INSERT INTO public.classroom_messages(room_id, user_id, display_name, message)
  VALUES (_room_id::text, actor, coalesce(actor_name, 'Learner'), clean_message)
  RETURNING * INTO sent;

  RETURN sent;
END;
$$;

REVOKE ALL ON FUNCTION public.send_classroom_message(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.send_classroom_message(uuid, text) TO authenticated, service_role;